### ISSUE TITLE
Update to the new SF SDK 1.4.87

### ISSUE THREAD

**Issue by SeanFeldman** [ParticularLabs/NServiceBus.ServiceFabric#1]
New public release https://azure.microsoft.com/en-us/documentation/articles/service-fabric-get-started/

**Comment by bbrandt** [comment]
Claus Sørensen provides a [guide for upgrading to the GA SDK](https://blog.geist.no/upgrading-azure-service-fabric/).
Other useful links:
https://blogs.msdn.microsoft.com/azureservicefabric/2016/05/13/community-round-up-may-2016/

**Comment by SeanFeldman** [comment]
Thank you @bbrandt 
Are you using SF persistence for NSB?

**Comment by bbrandt** [comment]
I am in very early stages of research on SF.  NServiceBus implementation still in the works.  Was just leaving myself some breadcrumbs in case I circle back around. :-)

**Comment by SeanFeldman** [comment]
Sounds good. If you have any questions, feel free to ping me.
From what it looks, persistence would be the only things that would benefit from SF native reliable collections. The rest is regular SF and NSB transport.

**Comment by 1TheMuffinMan** [comment]
@SeanFeldman I'm looking into using NSB with Azure SB transport in Service Fabric. The sample here doesn't seem to take into account that Service Fabric will want to run multiple instance of any particular service, so given a ThumbnailResizeService, how would you publish an event whereby only one instance of any particular service would handle it?

**Comment by SeanFeldman** [comment]
@1TheMuffinMan Could you please elaborate on ThumbnailResizeService? I'm not sure if I have the context. Thanks.

**Comment by 1TheMuffinMan** [comment]
@SeanFeldman It's just an arbitrary example of one of the services instead of saying Service A, B, C etc.

Consider you have two services running on 5 nodes, so 10 service instances total. If Service A publishes an event and Service B subscribes to it how can we ensure that only one instance of Service B handles the event?

**Comment by SeanFeldman** [comment]
In that case what you have is multiple _instances_ of your service (5 instances of each service).
When you publish an event, you publish a message, single one. One of the instances (no matter which one) will handle it (nature of competing consumers) since all instances compete over the same input queue. That's it. Hopefully this makes sense. It's no different from running with Cloud Services or WebJobs scaled out.

**Comment by 1TheMuffinMan** [comment]
@SeanFeldman Thanks for the clarification. I am new to NSB and SB in general and didn't catch that fundamental concept.

**Comment by SeanFeldman** [comment]
@1TheMuffinMan no worries at all. [Competing consumer pattern](https://msdn.microsoft.com/en-us/library/dn568101.aspx?f=255&MSPPError=-2147217396) is a powerful one. I highly recommend to look at one of the Azure transports doco: [ASB](docs.particular.net/nservicebus/azure-service-bus/) or [ASQ](https://docs.particular.net/nservicebus/azure-storage-queues/).

**Comment by 1TheMuffinMan** [comment]
@SeanFeldman Looking through this further I think what I actually want is something supported by the Distributor in order to remain in line with how Service Fabric works.

Here's an updated example:

- A user is added via the UserService and an event is published to subscribers
- The CompanyService has subscribed to that event and determines that the user should be added to a company
- At the same time an EmailNotification service was subscribed and sends an email to the user

So as you can see what I really want is a system where any unique service can receive the message, but only one instance of a particular service should handle that (probably round robin or another mechanism). It sounds like this is what I need https://docs.particular.net/nservicebus/msmq/distributor/publish-subscribe but I'll need to scrap ASB and use MSMQ apparently.

**Comment by yvesgoeleven** [comment]
@1TheMuffinMan You really should not use msmq in azure, it is highly discouraged by microsoft (and us). Follow the pattern that @SeanFeldman describes, it will give you exactly what you want. 1 instance (out of X instances) will pick up the message and process it. The distributor would be a way to achieve this very same thing keeping the remote limitations of msmq in mind, but ASB does not have these limitations as it can do competing consumer on it's own.

**Comment by 1TheMuffinMan** [comment]
@yvesgoeleven The problem with competing consumer is that while it works great for making sure only one instance of a service handles a message if we look at the bigger picture the real benefit from pub sub is the ability for multiple unique consumers to handle a message, but that becomes a problem when you have multiple services and multiple instances of each one. If you check out my example above your response it outlines what I'm after more clearly.

**Comment by yvesgoeleven** [comment]
@1TheMuffinMan exactly, that's how it works
